# Generated by Django 5.2.13 on 2026-04-12 07:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Batch identifier (e.g., Batch-2026-04-12)', max_length=255)),
                ('description', models.TextField(blank=True, default='', help_text='Optional batch description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'batches',
                'db_table': 'batches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('verified', 'Verified'), ('sent_to_customer', 'Sent to Customer')], default='draft', max_length=20)),
                ('verification_notes', models.TextField(blank=True, default='', help_text='QC manager notes')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='reports/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='core.batch')),
                ('generated_by', models.ForeignKey(blank=True, help_text='QC manager who generated this report', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Roll',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('roll_number', models.CharField(help_text='Roll identifier (e.g., R-001)', max_length=100)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order position in the batch scan queue')),
                ('avg_l', models.FloatField(blank=True, help_text='Average L* value', null=True)),
                ('avg_a', models.FloatField(blank=True, help_text='Average a* value', null=True)),
                ('avg_b', models.FloatField(blank=True, help_text='Average b* value', null=True)),
                ('delta_e', models.FloatField(blank=True, help_text='ΔE from batch centroid', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('scanned', 'Scanned'), ('accepted', 'Accepted'), ('warning', 'Warning'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('shade_group', models.PositiveIntegerField(blank=True, help_text='ML-assigned shade group number (1, 2, 3...)', null=True)),
                ('is_held', models.BooleanField(default=False, help_text='True if operator pressed Hold Roll on ESP32')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(help_text='The batch this roll belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='rolls', to='core.batch')),
            ],
            options={
                'db_table': 'rolls',
                'ordering': ['order', 'created_at'],
                'unique_together': {('batch', 'roll_number')},
            },
        ),
        migrations.CreateModel(
            name='ComparisonResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('delta_e_76', models.FloatField(help_text='CIE76 Delta E value')),
                ('delta_e_00', models.FloatField(help_text='CIEDE2000 Delta E value')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparison_results', to='core.batch')),
                ('roll_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparisons_as_roll1', to='core.roll')),
                ('roll_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparisons_as_roll2', to='core.roll')),
            ],
            options={
                'db_table': 'comparison_results',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('r', models.PositiveIntegerField(help_text='Red channel (0-255)')),
                ('g', models.PositiveIntegerField(help_text='Green channel (0-255)')),
                ('b', models.PositiveIntegerField(help_text='Blue channel (0-255)')),
                ('l_val', models.FloatField(help_text='CIELAB L* value')),
                ('a_val', models.FloatField(help_text='CIELAB a* value')),
                ('b_val', models.FloatField(help_text='CIELAB b* value')),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('roll', models.ForeignKey(help_text='The roll this scan belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='core.roll')),
            ],
            options={
                'db_table': 'scans',
                'ordering': ['-scanned_at'],
            },
        ),
    ]
