# Generated by Django 5.2.13 on 2026-04-12 08:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='ESP32 Color Sensor', max_length=100)),
                ('last_ping', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'device_status',
            },
        ),
    ]
