# Generated by Django 5.2.13 on 2026-04-12 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_devicestatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='client_a',
            field=models.FloatField(blank=True, help_text='Target a*', null=True),
        ),
        migrations.AddField(
            model_name='batch',
            name='client_b',
            field=models.FloatField(blank=True, help_text='Target b*', null=True),
        ),
        migrations.AddField(
            model_name='batch',
            name='client_b_rgb',
            field=models.PositiveIntegerField(blank=True, help_text='Render Target B', null=True),
        ),
        migrations.AddField(
            model_name='batch',
            name='client_g',
            field=models.PositiveIntegerField(blank=True, help_text='Render Target G', null=True),
        ),
        migrations.AddField(
            model_name='batch',
            name='client_l',
            field=models.FloatField(blank=True, help_text='Target L*', null=True),
        ),
        migrations.AddField(
            model_name='batch',
            name='client_r',
            field=models.PositiveIntegerField(blank=True, help_text='Render Target R', null=True),
        ),
        migrations.AddField(
            model_name='batch',
            name='target_roll',
            field=models.ForeignKey(blank=True, help_text='The internal reference roll', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='targeted_in_batches', to='core.roll'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='description',
            field=models.TextField(blank=True, help_text='Optional batch details'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='name',
            field=models.CharField(help_text='Batch identifier or name', max_length=100),
        ),
    ]
